Web/MyRecipes.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Common;
    using MyRecipes.Web.Controllers;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

Web/MyRecipes.Web/Controllers/BaseController.cs
namespace MyRecipes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

Web/MyRecipes.Web/Controllers/HomeController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyRecipes.Data;
    using MyRecipes.Services;
    using MyRecipes.Web.ViewModels;
    using MyRecipes.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private readonly ApplicationDbContext db;
        private readonly ISupichkaScraperService scraperService;

        public HomeController(ApplicationDbContext db, ISupichkaScraperService scraperService)
        {
            this.db = db;
            this.scraperService = scraperService;
        }

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel
            {
                CategoriesCount = this.db.Categories.Count(),
                ImagesCount = this.db.Images.Count(),
                IngredientsCount = this.db.Ingredients.Count(),
                RecipesCount = this.db.Recipes.Count(),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> SeedRecipes()
        {
            await this.scraperService.DbRecipeSeeder();

            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/MyRecipes.Web/Controllers/RecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels.Recipes;

    public class RecipesController : Controller
    {
        private readonly ICategoriesService categoriesService;

        public RecipesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateRecipeInputModel();
            viewModel.CategoriesItems = this.categoriesService.GetAllCategories();
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(CreateRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllCategories();
                return this.View(input);
            }

            //// TODO: Create recipe using service method
            //// TODO: Redirect to recpie info page

            return this.RedirectToAction("/");
        }
    }
}

Web/MyRecipes.Web/Views/Home/Index.cshtml
@using MyRecipes.Common
@model MyRecipes.Web.ViewModels.Home.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to @GlobalConstants.SystemName!</h1>
    <div class="col-md-4 offset-md-4">
        <p>We have:</p>
        <ul class="list-group">
            <li class="list-group-item bg-light">Recipes: @Model.RecipesCount</li>
            <li class="list-group-item bg-danger">Categories: @Model.CategoriesCount</li>
            <li class="list-group-item bg-light">Images: @Model.ImagesCount</li>
            <li class="list-group-item bg-danger">Ingredients: @Model.IngredientsCount</li>
        </ul>
    </div>
</div>

<div class="text-center">
    <br />
    <a class="btn btn-primary" asp-controller="Home" asp-action="SeedRecipes">Seed recipes from supichka.com</a>
</div>

Web/MyRecipes.Web/Views/Recipes/Create.cshtml
@model MyRecipes.Web.ViewModels.Recipes.CreateRecipeInputModel
@{
    this.ViewData["Title"] = "Add new recipe";
    var categoryItems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key));
}

<h1>Add new recipe</h1>

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group col-md-6">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="Instructions"></label>
        <textarea asp-for="Instructions" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Instructions" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="PreparationTime"></label>
        <input asp-for="PreparationTime" class="form-control" />
        <span asp-validation-for="PreparationTime" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="CookingTime"></label>
        <input asp-for="CookingTime" class="form-control" />
        <span asp-validation-for="CookingTime" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="PortionsCount"></label>
        <input asp-for="PortionsCount" class="form-control" />
        <span asp-validation-for="PortionsCount" class="text-danger"></span>
    </div>
    <div class="form-group col-md-6">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItems"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <input type="submit" class="btn btn-primary" />
</form>

Web/MyRecipes.Web/Views/Shared/_Layout.cshtml
@using MyRecipes.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>